### PR TITLE
Hard-coding fix to link issues in publications.

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Really need to fix this... Issue doesn't show up when loading locally, but does when on master.

### CODE REVIEW

**Comment by bqpd** [comment]
huh, those links were working for me on master!

**Comment by bqpd** [comment]
oh browsers

**Comment by 1ozturkbe** [comment]
... yeah...

**Comment by 1ozturkbe** [comment]
It's the worst, because it works when I build the website locally, and totally fails in browser. That is why I have been approving tons of pull requests of my own.

**Pull request merged**
