### PR TITLE
JHO video on homepage, and refine group mission statement

### PR DESCRIPTION
**Pull request by whoburg**
ready for review, will merge soon if no review. If you see problems, please make the changes as I need to step away from computer for a bit

### CODE REVIEW

**Comment by whoburg** [comment]
can someone review and merge this asap?

**Comment by 1ozturkbe** [comment]
Can't review, Internet horrible. @bqpd let me know if you can do this.

**Comment by bqpd** [comment]
just woke up; on it, sorry for the delay!

**Comment by whoburg** [comment]
awesome thanks Ned! just in time. going offline for next 6 hrs or so

**Comment by bqpd** [comment]
I think it's all set now

**Comment by 1ozturkbe** [comment]
You are a champion Ned. Just on time!

**Pull request merged**
